import { z } from "zod";

export const monitorSchema = z.object({
	type: z.enum([
		"http",
		"ping",
		"docker",
		"port",
		"game",
		"grpc",
		"pagespeed",
		"hardware",
		"websocket",
	]),
	url: z.string().min(1, "URL is required"),
	name: z.string().min(1, "Name is required"),
	port: z.number().optional(),
	gameId: z.string().optional(),
	grpcServiceName: z.string().optional(),
	secret: z.string().optional(),
	interval: z.number(),
	statusWindowSize: z.number(),
	statusWindowThreshold: z.number(),
	notifications: z.array(z.string()).default([]),
	escalationRetries: z.number().min(0).max(10).default(0),
	escalationNotifications: z.array(z.string()).default([]),
	ignoreTlsErrors: z.boolean().optional(),
	useAdvancedMatching: z.boolean().optional(),
	matchMethod: z.enum(["equal", "include", "regex", ""]).optional(),
	expectedValue: z.string().optional(),
	jsonPath: z.string().optional(),
	geoCheckEnabled: z.boolean().optional(),
	geoCheckLocations: z.array(z.string()).optional(),
	geoCheckInterval: z.number().optional(),
	cpuAlertThreshold: z.number().optional(),
	memoryAlertThreshold: z.number().optional(),
	diskAlertThreshold: z.number().optional(),
	tempAlertThreshold: z.number().optional(),
	selectedDisks: z.array(z.string()).optional(),
});

export type MonitorFormData = z.infer<typeof monitorSchema>;
